/**
 * Các địa điểm trong tên tiếng Anh của đơn vị phân loại mà nên được giữ nguyên kiểu viết hoa khi định dạng. Các từ này cũng được dùng khi thu thập để xác định nếu tên tiếng Anh là một địa điểm chứ không phải tên đơn vị phân loại.
 */
export const placeNames: (string | RegExp)[] = [
	'Africa',
	'African',
	'American',
	'Angolan',
	'Asian',
	'Atlantic',
	'California',
	'Cambodia',
	'Carolina',
	'Caspian',
	'Cerro Brujo',
	'Colombia',
	'Con Dao',
	'Costa Rican',
	'Cuban',
	'Chinese',
	'Dominican',
	'Egyptian',
	'Eurasian',
	'European',
	'Himalayan',
	'Indian Ocean',
	'Indian',
	'Indonesia',
	'Indonesian',
	'Japanese',
	'Korean',
	'Madagascar',
	'Moroccan',
	'New Zealand',
	'Pacific',
	'Panama',
	'Peru',
	'Puerto Rican',
	'Sri Lanka',
	'Timor',
	'Vietnamese',
	'Yunnan',
	'Old World',
	'New World',
	/\b\S+ Islands\b/,
	/\b\S+ Mountains\b/
]
