export const comboPhotoCaptionsMap: Record<string, string> = {
	mr: ' % photoCode ; .',
	'a+mr': ' % photoCode ; adult',
	'a+n+mr': ' % photoCode ; antler',
	'b+mr': ' % photoCode ; breeding',
	'c+mr': ' % photoCode ; reconstruction',
	'c+t+mr': ' % photoCode ; caterpillar',
	'd+mr': ' % photoCode ; drawing',
	'd+m+mr': ' % photoCode ; dark morph',
	'f+mr': ' % photoCode ; fossil',
	'f+l+mr': ' % photoCode ; flower',
	'f+r+mr': ' % photoCode ; fruit',
	'h+mr': ' % photoCode ; holotype',
	'i+mr': ' % photoCode ; immature',
	'i+p+mr': ' % photoCode ; initial phase',
	'j+mr': ' % photoCode ; juvenile',
	'j+a+mr': ' % photoCode ; jaw',
	'k+mr': ' % photoCode ; skeleton',
	'l+mr': ' % photoCode ; illustration',
	'l+m+mr': ' % photoCode ; light morph',
	'm+mr': ' % photoCode ; mandible',
	'n+mr': ' % photoCode ; nymph',
	'n+b+mr': ' % photoCode ; non-breeding',
	'p+mr': ' % photoCode ; paratype',
	'p+h+mr': ' % photoCode ; photograph',
	'q+mr': ' | photoCode ; .',
	'r+mr': ' % photoCode ; restoration',
	's+mr': ' % photoCode ; specimen',
	't+mr': ' % photoCode ; teeth',
	't+r+mr': ' % photoCode ; tree',
	't+o+mr': ' % photoCode ; tooth',
	't+p+mr': ' % photoCode ; terminal phase',
	'u+mr': ' % photoCode ; skull',
	'u+d+mr': ' % photoCode ; underside',
	'u+p+mr': ' % photoCode ; upperside',
	'v+mr': ' % photoCode ; larva',
	'w+mr': ' / photoCode ; .',
	'x+mr': ' % photoCode ; exhibit'
}
