/**
 * Các địa điểm trong tên tiếng Anh của đơn vị phân loại mà nên được giữ nguyên kiểu viết
 * hoa khi định dạng. Các từ này cũng được dùng khi thu thập để xác định nếu tên tiếng Anh
 * là một địa điểm chứ không phải tên đơn vị phân loại.
 */
export const placeNames: (string | RegExp)[] = [
	'Afghanistan',
	'Africa',
	'African',
	'Algeria',
	'American',
	'Andes',
	'Angolan',
	'Argentina',
	'Armenia',
	'Asian',
	'Atlantic',
	'Australia',
	'Australian',
	'Austria',
	'Balkan',
	'Bermuda',
	'Bolivia',
	'Borneo',
	'Brazil',
	'California',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Caribbean',
	'Carolina',
	'Caspian',
	'Cerro Brujo',
	'Chile',
	'China',
	'Chinese',
	'Colombia',
	'Con Dao',
	'Congo',
	'Costa Rica',
	'Costa Rican',
	'Cuba',
	'Cuban',
	'Dominican',
	'Ecuador',
	'Egypt',
	'Egyptian',
	'El Salvador',
	'Eurasian',
	'Europe',
	'European',
	'France',
	'Guatemala',
	'Himalaya',
	'Himalayan',
	'Hispaniola',
	'Honduras',
	'Hong Kong',
	'Iberian',
	'India',
	'Indian Ocean',
	'Indian',
	'Indonesia',
	'Indonesian',
	'Iran',
	'Israel',
	'Italy',
	'Ivory Coast',
	'Jamaica',
	'Japan',
	'Japanese',
	'Kazakhstan',
	'Kenya',
	'Korea',
	'Korean',
	'Lebanon',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Mediterranean',
	'Mexico',
	'Moroccan',
	'Myanmar',
	'Namibia',
	'Nepal',
	'New Caledonian',
	'New Guinea',
	'New World',
	'New Zealand',
	'Old World',
	'Pacific',
	'Panama',
	'Papuan',
	'Peru',
	'Philippine',
	'Portugal',
	'Puerto Rican',
	'Puerto Rico',
	'Romania',
	'Russia',
	'Russian',
	'Siberian',
	'South America',
	'Spain',
	'Sri Lanka',
	'Sri Lankan',
	'Taiwan',
	'Tajikistan',
	'Tanzania',
	'Timor',
	'Turkey',
	'United States',
	'Uruguay',
	'USA',
	'Venezuela',
	'Vietnam',
	'Vietnamese',
	'Yunnan',
	/\b\S+ Islands\b/,
	/\b\S+ Mountains\b/,
	/\bMt\. \S+\b/
]
